import{S as d,i}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u=new d(".gallery-item",{captionsData:"alt",captionDelay:250}),f=document.getElementById("search-form"),c=document.getElementById("gallery"),a=document.getElementById("loading-spinner");f.addEventListener("submit",async l=>{l.preventDefault();const r=document.getElementById("search-input").value.trim();if(!r){i.warning({title:"Uyarı",message:"Lütfen bir arama terimi girin!"});return}try{a.style.display="block";const n=await(await fetch(`https://pixabay.com/api/?key=46164011-db8308970fd829f53e85acb75&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`)).json();if(await new Promise(e=>setTimeout(e,2e3)),n.hits.length===0){i.error({title:"Hata",message:"Görsel bulunamadı. Lütfen tekrar deneyin!"});return}c.innerHTML="",n.hits.forEach(e=>{const t=document.createElement("a");t.href=e.largeImageURL,t.classList.add("gallery-item"),t.innerHTML=`
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Comments: ${e.comments}</p>
          <p>Views: ${e.views}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      `,c.appendChild(t)}),u.refresh()}catch(o){a.style.display="none",i.error({title:"Hata",message:"Bir sorun oluştu. Lütfen tekrar deneyin!"}),console.error("Bir hata oluştu:",o)}finally{a.style.display="none"}});
//# sourceMappingURL=index.js.map
